### ISSUE TITLE
Make an option for instant entry

### ISSUE THREAD

**Issue by Algram** [tebelorg/TagUI#62] opened 2017-10-18 19:04 UTC
I would like to have the option to make the `type` command input a string instantly, instead of writing it character by character.
This would speed up our tests significantly.

Thanks a lot for your help!

**Comment by kensoh** [comment] 2017-10-19 07:41
Hi @Algram this is out of scope for TagUI steps, because a normal user behavior will be to type character by character and let the website event-handling code run as designed for validation, or for some other backend code to run in response to the inputs.

If you want to do that, you can try using the dom step to manipulate the HTML DOM directly, below are 2 examples, one by setting value directly and one setting value by using a variable. Note that this way may cause unexpected behavior from not triggering the normal website inputs events.

```
https://app.convertkit.com/users/signup?plan=3k

// set value directly
dom document.querySelector('#email').value = 'test@test.com'

// set using variable
dom_json = '12345678'
dom document.querySelector('#password').value = dom_json

// wait to see effect
wait

// save screenshot
snap page
```

**Closed** 2017-10-22 13:27 UTC
Labels: query
