### ISSUE TITLE
Q: Dynamic URL

### ISSUE THREAD

**Issue by thim81** [tebelorg/TagUI#37] opened 2017-07-31 10:54 UTC
Hi @kensoh 

How can I open an URL with dynamic data?

Example:

https://www.google.be/search?q=tagUI

Flow 

```
data_keyword = "tagUI";

https://www.google.be/search?q='+data_keyword+'
```

Complains`ERROR - [LINE x] invalid URL https://www.google.be/search?q='+data_keyword+'`

**Comment by kensoh** [comment] 2017-07-31 14:45
Hi @thim81 thanks for raising this! I haven't considered this use case before. Can you tell me more what options you run your flow with and provide a simple flow which gives this error?

When I run below, it will work for chrome option but will fail for default (PhantomJS) or firefox option, with some error saying data_keyword not defined. The reason for the error is variables are being declared within CasperJS context. When calling casper.thenOpen() it will not be accessible as it is in the global context.
```
http://tebel.org/index_mobile.php
data_keyword = "interface_automation";
http://tebel.org/gist/'+data_keyword+
```

Changing the flow to below works. Because { and } will be converted into CasperJS blocks to make the context in CasperJS. For other TagUI steps, variables and parameters are by default already placed in CasperJS context and does not require below. Not sure if there's an easier way for this, without creating unnecessary nesting for cases without dynamic variables in URL.

```
http://tebel.org/index_mobile.php
data_keyword = "interface_automation";
{
http://tebel.org/gist/'+data_keyword+'
}
```

Lastly, to add on, using datatables, having dynamic variables from the datatable fed into URL will work. As the generated scripts fetch from the csv datatable directly before generating the .js file.

**Comment by kensoh** [comment] 2017-07-31 14:57
Adding on, I think it is better to make some provision to handle this use case without user having to put in { and } manually. At some point in time when calling dynamic url, some user or myself will forget to put this and the script will fail. Waste time troubleshooting then find out / remember.

Handling it automatically is more consistent behaviour with rest of TagUI steps. Probably can add some conditions in tagui_parse.php -> url_intent() to address this. Will still hear more from you on how you replicate the error message.

**Comment by thim81** [comment] 2017-07-31 15:52
Now I understand better the use cases for the {} block

An example flow to replicate the error on Firofox:

`./src/tagui ./sample/2_verify_mail firefox test`

```
http://www.mailinator.com/v2/inbox.jsp?zone=public

// = MOCKING ========================================================= //

// Mocking data
data_random = Math.floor(Math.random()*200);
data_test = "hyper.koopa.bowser" + data_random;

// = Mailinator ================================================================= //
// http://www.mailinator.com/v2/inbox.jsp?zone=public&query=hyper.koopa.bowser
http://www.mailinator.com/v2/inbox.jsp?zone=public&query='+data_test+'
wait 3.0

**Comment by kensoh** [comment] 2017-07-31 16:48
When I try running above exactly I still cannot get the error
`ERROR - [LINE x] invalid URL https://www.google.be/search?q='+data_keyword+'`

The error I got was the expected one on data_test not defined, that error can be fixed by enclosing with the { and } brackets. The only other possible cause I can think of is maybe our difference in PHP version. I tried on mine is v5.6.30 (macOS and CentOS). Below is the line in the parsing where the error can appear, it uses a PHP function to decide whether a URL is valid or not.

```php
if (filter_var($raw_intent, FILTER_VALIDATE_URL) == false)
```

Really strange.. If the cause of this is not resolved, even after adding automatic handling of context for dynamic URL I think you will still get the same error.

**Comment by thim81** [comment] 2017-08-01 09:52
When I run the flow 

```
http://www.mailinator.com/v2/inbox.jsp?zone=public

// = MOCKING ========================================================= //

// Mocking data
data_random = Math.floor(Math.random()*200);
data_test = "hyper.koopa.bowser" + data_random;

// = Mailinator ================================================================= //
// http://www.mailinator.com/v2/inbox.jsp?zone=public&query=hyper.koopa.bowser
http://www.mailinator.com/v2/inbox.jsp?zone=public&query='+data_test+'
wait 3.0
```
With the following command:
`tagui $ ./src/tagui ./samples/test_dynamic_url firefox test debug`

```
Test file: /Users/Sites/localhost/tagui/samples/test_frame.js              
Tue Aug 01 2017 11:50:19 GMT+0200 (CEST) 
# /Users/Sites/localhost/tagui/samples/test_frame 
[info] [phantom] Starting... 
FAIL ReferenceError: data_test is not defined 
#    type: uncaughtError 
#    file: /Users/Sites/localhost/tagui/samples/test_frame.js 
#    error: {} 
#    stack: not provided 
PASS /Users/Sites/localhost/tagui/samples/test_frame (NaN test) 
FAIL 1 test executed in 0.245s, 0 passed, 1 failed, 0 dubious, 0 skipped.        

Details for the 1 failed test:
 
In /Users/Sites/localhost/tagui/samples/test_frame.js 
  /Users/Sites/localhost/tagui/samples/test_frame 
    uncaughtError: ReferenceError: data_test is not defined 
Result log stored in /Users/Sites/localhost/tagui/samples/test_frame.xml   

```

**Comment by thim81** [comment] 2017-08-01 09:54
When using the *{}* it works like a charm

```
http://www.mailinator.com/v2/inbox.jsp?zone=public

// = MOCKING ========================================================= //

// Mocking data
data_random = Math.floor(Math.random()*200);
data_test = "hyper.koopa.bowser" + data_random;

// = Mailinator ================================================================= //
{
http://www.mailinator.com/v2/inbox.jsp?zone=public&query='+data_test+'
}
wait 3.0
```

**Comment by thim81** [comment] 2017-08-01 11:29
On this topic, it is not possible to use a full variable?

```
https://github.com

data_test = "https://github.com/tebelorg/TagUI/";
{
'+data_test+'
}
```

Error:

```
ERROR - [LINE 5] cannot understand step '+data_test+'
ERROR - automation aborted due to above
```

**Comment by thim81** [comment] 2017-08-01 11:34
Adding a http:// in front, makes the URL validation fail, which is logical.

```
https://github.com/

data_test = "https://github.com/tebelorg/TagUI/";

{
https://'+data_test+'
}
```

Error:
```
ERROR - [LINE 7] invalid URL http://'+data_test+'
ERROR - automation aborted due to above
```

**Comment by kensoh** [comment] 2017-08-01 11:47
Yes, that's correct, I've just replied on your other issue - https://github.com/tebelorg/TagUI/issues/41

"Yes this is expected, TagUI works by letting users convey their intention through various steps + JS code as needed. It will check if the line starts with http:// or https:// to detect that user wants to access an URL. In this case '+api_json.link+' is a variable and it doesn't convey that intention, so it throws error. It should work if the URL is broken down to http://'+api_json.link+' etc where api_json.link is github.com/tebelorg/TagUI instead of https://github.com/tebelorg/TagUI."

As it works for you with { and } for now, I'll leave this issue open for my tracking to implement automatic setting of context if user tries to pass variable when calling an URL.

**Comment by kensoh** [comment] 2017-08-01 11:50
Adding on, for eg in JavaScript, we can't really define a variable as a string JS statement, then type that variable on an empty line by itself to execute the statement. JS can use eval. For TagUI the parsing happens before the execution, when natural-language-syntax converts into JS code. Such replacements will work if they are provided from data tables, as it is still within control during parsing.

**Comment by thim81** [comment] 2017-08-01 12:43
I solved it like this but this feels very dirty, so perhaps I'm missing a better way

```
https://github.com/

//api_config.header[0] = 'Header1: value1';
api http://demo3796957.mockable.io/test
echo api_result
echo 'Link - ' + api_json.link

link = api_json.link.replace('https://github.com/','');
echo link

{
  https://github.com/'+link+'
}
```

**Comment by kensoh** [comment] 2017-08-01 15:00
You can just remove the https:// or http:// portion, the key is to have a url header in front so it can be treated that user has intention to visit URL. Otherwise by specifying a variable, TagUI has no context what to do with the variable. After the enhancement is put in, it would be cleaner without { & }.

Other frameworks or CasperJS will have a method eg thenOpen or start or gotoURL etc to call a navigation step with the URL as variable. Having http:// or https:// in front looks ok to me and is probably the most simplified form of calling an URL with variable handling.

There is a little potential to improve by replacing duplicated https://https://github.com, but may be over-engineering on an edge case that can make debugging hard later on for other majority use cases. Another option I can think of is create a new step url so access to url becomes url http://abc.xyz etc. But again, supporting this edge case of using full url variable directly makes the other majority of use cases less convenient.

**Comment by kensoh** [comment] 2017-08-01 15:07
Don't worry too much about the hack. TagUI itself is basically a hack to get around all the programming constructs / nested structures for handling web automation. Whatever works is ok. 

Even for steps I add different names such as click / tap, enter / type etc. And for conditions equal or equals, the various lesser / greater etc. I try to have multiple ways to create the same specific outcome, so users who are not too experienced can still make something work easily. Of course, this goes against the idea of strongly typed programming languages for scalability reasons, but it can be interpreted both ways.

**Comment by kensoh** [comment] 2017-08-04 15:43
@thim81 I've updated readme doc with a number of improvements with reference to few of the questions you raised. Also, made a [commit](https://github.com/tebelorg/TagUI/commit/dadc6b292eff02e3dc1ce630cc5db0812a2a49c4) in master with following comment. So that dynamic URLs can be used out of the box without having to specify { and } block. Removed URL validation for dynamically formed URLs in order to reduce chance of triggering false error. Thanks for your inputs!

```
Before this commit, URLs containing variables have to be explicitly set
in { and } block in order to retain the casper context for variables.
With this commit, that is done automatically.

So the lines below will now work. Also, url validation is only done for
raw text url in order not to trigger error for dynamically formed URLs.

link = “abc.com”;
https://'+link+'
```

**Closed by kensoh** 2017-08-04 15:43 UTC
Labels: enhancement
