### ISSUE TITLE
Chrome extension: problem recording input changes (multiple fields)

### ISSUE THREAD

**Issue by klichukb** [tebelorg/TagUI#53] opened 2017-09-03 23:24 UTC
Hello. Thanks for a great tool.

I have a simple web form ("send a comment" type) with 3 fields. Recording the changes using a chrome extension 2.4.0.

Actions:
Typing "Text1", "Text2", "Text3" in each field respectively.

Log shows:

```
click comments
enter comments as Test1Test2Test3
```

It glued 3 separate field edits into one..

The HTML for the web form is:

```
 <form action="http://filvarok.info/wp-comments-post.php" method="post" id="commentform" class="comment-form">
        <div class="blog-form-group-textarea">
            <textarea id="comments" rows="5" class="blog-form-control-textarea" name="comment" type="text" placeholder="Comment:"></textarea>
        </div>
        <div class="blog-form-group">
            <input class="blog-form-control" name="author" id="author" value="" type="name" placeholder="Name:">
        </div>
        <div class="blog-form-group">
            <input class="blog-form-control" name="email" id="email" value="" type="email" placeholder="Email:">
        </div>
        <p class="form-submit">
            <input name="submit" type="submit" id="blogdetail_btn" class="submit" value="Send">
            <input type="hidden" name="comment_post_ID" value="140" id="comment_post_ID">
            <input type="hidden" name="comment_parent" id="comment_parent" value="0">
        </p>
 </form>

```

**Comment by kensoh** [comment] 2017-09-05 00:52
Hi @klichukb thanks for raising this. The recorder is based on [Resurrectio / Zope](https://github.com/ebrehault/resurrectio) recording engine and has some limitations such as recording popups / frames / tab keys for example.

How is the UI interaction like in this website? From the raw HTML it looks like there is a single textarea web-element with id 'comments', and the recorder records the inputs text1 text2 text3 in that web element. How do you manually navigate in the UI to enter into the 3 separate fields?

If it is by tab key I'm afraid it won't work as the engine can't pick up certain keys such as tab or backspaces (specifically it was designed to handle keypress events but certain special keys are interpreted by browsers as keyup or keydown events).

**Comment by klichukb** [comment] 2017-09-05 21:02
Hey, @kensoh. Thanks for response. I was tabbing through the inputs.

But I guess I have a good news. I just substituted latest recorder.js from Resurrectio into TagUI chrome extension and the tabbing works great. I'm not sure if everything else is still compatible with the extension and what changes does TagUI introduce to this file, but as far as good!

Please try to update recorder from Resurrection repo.

**Comment by kensoh** [comment] 2017-09-06 06:01
Thanks @klichukb :) how are the recorded inputs for you look like in above webpage example?

When I tried the recorder.js, I found that it creates 2 lines, one for entering text in the first field and one for entering text in the 2nd field. I've made major changes to it to support TagUI-related steps such as right-clicking to see the list of TagUI shortcuts. 
```
enter email as test@test.com
enter password as 123456
```

**NOTES**
recorder.js same as what was used to create extension (except patch on form with name element), still doesn't record tab key as input keypress but able to capture entering text in next field after tab key is pressed. must be bug introduced when converting extension to tagui format. to check if can remove bug at the same time retaining existing tagui chrome extension functionality.

**Comment by kensoh** [comment] 2017-09-06 07:18
Committed with following comments. Updated npm package, publishing in progress to Chrome web store. The extension should auto-update by tomorrow the next time Chrome is restarted. Hopefully that works for your use case, it did for the sample website I used to tab between fields and enter text.

- update readme on tab key input verbiage (tab keys can’t be captured as inputs but tabbing to next field works)

- update chrome extension upstream patch from resurrectio on issue when a form as an element with the name ‘name’ it will have issue

- update chrome extension recorder.js onchange event. the event was previously changed to enable a custom function in handling drop down option selection. but there are edge cases such as tabbing to next field which will not work with that change. this update handle both the 2 scenarios depending on whether the event is for a dropdown option selection or for everything else (the original resurrection code)

**Comment by klichukb** [comment] 2017-09-06 09:37
Great. Sorry about not mentioning what exactly i discovered about tabbing. Initially tabbing through inputs was an issue for me, not capturing Tab key presses, hence i haven't event noticed these are not recorded :)

At least the input events are not glued together and the test cases generated look correct.

Thanks for updates, @kensoh !

**Closed** 2017-09-06 09:45 UTC
Labels: bug
