### ISSUE TITLE
Recording of file input selection cannot work

### ISSUE THREAD

**Issue by prinspark** [tebelorg/TagUI#48] opened 2017-08-15 06:10 UTC
I'm back,kensoh:)
I wanna upload an image to server by file input box recently , but TAGUI just record 'click .file-upload-btn input'.
Is it a defect of casperjs?

**Comment by kensoh** [comment] 2017-08-15 06:24
Hi @prinspark it has been a while :)

I see, uploading files is usually restricted by automation due to security reasons. Imagine a JS script has the ability to upload some private file on your laptop to their web-server. So by design, most browsers force this to be done by user manual action. For the TagUI Chrome extension, it is based on Resurrectio project and also does not record the OS events when user choose a file from the file manager, because during headless automation this file manager popup does not happen.

There is some method provided by PhantomJS and Chrome also has made a provision for setting this manually without simulating that file explorer popup box. I recently added a new TagUI step upload to do that. You can try if that works for you. Syntax is `upload css-selector filename`

https://github.com/tebelorg/TagUI#steps-description

**Comment by prinspark** [comment] 2017-08-15 07:03
`upload .file-upload-btn ~/imagetopost.jpg`
Is that right?

**Comment by prinspark** [comment] 2017-08-15 07:07
Or use full css selector  below?

#app > div > from > div:nth-child(10) > div > div > div > div:nth-child(1) > div.file-upload-btn.has-img > input[type="file"]

**Comment by kensoh** [comment] 2017-08-15 07:07
Not sure if ~ will work for the file name expansion, you can try `upload .file-upload-btn input as filename` where .file-upload-btn input is the css-selector for the file input button, and filename can be relative path or full path on your laptop.

During testing, I validated the step works for imgur.com for both PhantomJS and Chrome.

**Comment by kensoh** [comment] 2017-08-15 07:12
If file-upload-btn is the classname .file-upload-btn might be able to work already.

When I tried with imgur.com don't need full path of css. If it is ID identifier it will be #element

**Comment by prinspark** [comment] 2017-08-15 07:35
ok , and how to restrict click href action to open within current window or page?

**Comment by kensoh** [comment] 2017-08-15 07:52
I think that's controlled purely by the website. There is attribute to force open on a new window/tab versus on the same window/tab. If you are familiar with CasperJS and running TagUI in default mode (CasperJS + PhantomJS) then you can try hacking using below function. May be try getting that href value into a variable. http://docs.casperjs.org/en/latest/modules/casper.html#getelementattribute

Then decompose to get the domain name + rest of URL, or form an URL if the href is relative href.

Then use the navigation step https:// or http://'+variable+' to go to that URL directly. This is quite hacky and not straightforward but may be possible if you are familiar with CasperJS and if that webpage able to retrieve that href value.

**Comment by prinspark** [comment] 2017-08-15 08:06
The recorded  flow file stuck in element locating when jump to a new page.So I guess, it might be caused by this reason. Any solution?

**Comment by kensoh** [comment] 2017-08-15 08:14
Do you mean that recording fails once you clicked on a link to a new page, and the things you do on the new page cannot be recorded? If yes, that's expected as the Resurrectio recorder cannot record new events on the new popups, I believe.

Also, the recording is not foolproof, more to help reduce typing manually all the steps and identifier.  Normally for automation, I still do manually using the web browser inspector to select the best identifier to be used.

The steps after that popup window might still be able to enter manually, but you will need to use popup step to specify some URL string to look for in the popup window, so that the next step will be executed in that popup window. If there are multiple steps you can do like below - 

```
popup string_in_url_of_popup_window
{
click aaa
type bbb as ccc
click ddd
}
```

https://github.com/tebelorg/TagUI#steps-description

**Comment by prinspark** [comment] 2017-08-15 08:22
Nope, it can be recorded.
But when I try to replay the flow file, it responses an error 'can not find element'.

**Comment by kensoh** [comment] 2017-08-15 08:27
Did you try adding the popup step like above comment?

**Comment by kensoh** [comment] 2017-08-15 08:29
Yeah just checked the Resurrectio source code, can't work properly with popups or framesets 

`//caveats: popup windows undefined, cant handle framesets`

**Comment by prinspark** [comment] 2017-08-16 08:58
So it means automation can't go on unless all actions stay in one tag page?

**Comment by kensoh** [comment] 2017-08-16 09:11
Did you try adding the popup step like above comment? Need to use popup step to define the context which tab / webpage you want to automate. Otherwise CasperJS or Chrome won't know which element you are referring to on the webpage if there are multiple web pages open.

```
popup string_in_url_of_popup_window
{
click aaa
type bbb as ccc
click ddd
}
```

**Comment by kensoh** [comment] 2017-08-16 09:16
Closing the issue for now, as recording popup is not supported by Resurrectio (the tool that the Chrome extension is base on). For manual editing, popup step and frame step can be used to set the context of where to take action. More details above and in https://github.com/tebelorg/TagUI#steps-description

**Closed by kensoh** 2017-08-16 09:16 UTC
Labels: feedback, pending-response
