### ISSUE TITLE
How to run using npm after npm install tagui

### ISSUE THREAD

**Issue by kmahalingpur** [tebelorg/TagUI#69] opened 2017-11-09 12:36 UTC
Hi i am new to tagui i need guidelines for how to run tagui after npm install in windows

thanks in advance :)

**Comment by kensoh** [comment] 2017-11-09 14:48
Hi @kmahalingpur, after npm install, you can go to the tagui\src folder and type `tagui samples\1_yahoo` to try out the [automation examples](https://github.com/tebelorg/TagUI#flow-samples). Using npm install assumes you already have PHP on your Windows. If not, you can use the [packaged installation for Windows](https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI_Windows.zip) to unzip and run instead.

Run direct from normal Windows command prompt, not inside a Win-Linux shell (cygwin / mingw32)

**Comment by kmahalingpur** [comment] 2017-11-10 08:30
Thanks for the quick reply.... Did the same thing but got error for GNU utilities and curl so did manual addition in /src/unx. It would be better if it was provided in npm install.

**Comment by kensoh** [comment] 2017-11-10 09:49
Thanks for your reply @kmahalingpur it looks like the unix commands for Windows are not available. Have you tried downloading the packaged installation for Windows from the link above? After unzipping and run from tagui\src folder do you get the find command not found message?

I don't think it is good to include those Windows executables for Linux commands as part of the npm package. Because npm install tagui for macOS or Linux will also get many large-sized Windows files. Too many other Windows-specific dependencies such as PHP installation and Linux commands. Will be better to use the [Windows zip](https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI_Windows.zip) directly.

Updated readme to use npm install only for macOS/Linux, committed with following comment - 

"Windows has additional dependencies as such PHP distribution, and Windows versions of Linux-based commands. It would be troublesome to npm install tagui on a clean Windows environment without those dependencies. Better to use the Windows packaged installation file directly -> unzip and run (all dependencies are packaged in)"

**Comment by kensoh** [comment] 2017-11-10 19:34
Adding on, can you share more info how to replicate the find error message? For eg, the full path and filename of the flow file, from which directory and what command you use to run tagui on the file.

For Windows, some TagUI features such as making API calls and running automation files stored on cloud URL requires that Windows find command to work correctly for the features to work.

**Comment by kmahalingpur** [comment] 2017-11-11 07:48
@kensoh  That find issue came when i try to do with npm install. Process i followed was 

npm install tagui
set the src path in path variable
downloaded gnc utilites and curl in /src/unx folder
Run sample case
Test case ill be success but that find error will be there.

And as u mentioned earlier to use zip for windows i tried but shows dll missing so need to add that dll manually???

**Comment by kensoh** [comment] 2017-11-11 08:56
I'm afraid I can't reproduce your issue, when I download the Windows zip -
https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI_Windows.zip

After unzip, there are already the Linux commands in tagui\src\unx folder. There is also PHP distribution in tagui\src\php folder. Below is what happens after I unzip to c:\tagui folder -> Windows start menu -> Run -> cmd -> cd \tagui\src -> tagui samples\1_yahoo

![capture](https://user-images.githubusercontent.com/10379601/32687831-05e0fdd4-c700-11e7-800a-e84e5d9cccd2.PNG)

Without providing more info I asked for - where tagui is unzipped on your laptop, and the exact commands you use to run, I won't be able to troubleshoot further on the message on your PC. I ran above on Windows 8, and recently tried running TagUI automation flow ok on Windows 10.

**Comment by kmahalingpur** [comment] 2017-11-13 09:22
@kensoh installed in the same manner u told still dll issue.
![image](https://user-images.githubusercontent.com/14965294/32718152-357e1bd4-c882-11e7-938a-c5ec7d87355f.png)

Im running it on win10

**Comment by kensoh** [comment] 2017-11-13 10:52
Thanks @kmahalingpur for sharing, it looks like on your PC a core Windows system file msvcr110.dll is missing or corrupted, so PHP execution engine cannot run. I found below article with some steps to fix that file, for example [downloading from Microsoft website here](https://www.lifewire.com/how-to-fix-msvcr110-dll-not-found-or-missing-errors-2623800).

https://www.lifewire.com/how-to-fix-msvcr110-dll-not-found-or-missing-errors-2623800

**Comment by kensoh** [comment] 2017-11-18 08:38
closing for now but do let me know if there's update!

**Closed by kensoh** 2017-11-18 08:38 UTC
Labels: query
